apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.fullname" . }}-creds
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.rootPassword | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "minio.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "minio.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "minio.selectorLabels" . | nindent 8 }}
      {{- if .Values.monitoring.enabled }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.service.port | quote }}
        prometheus.io/path: /minio/v2/metrics/cluster
      {{- end }}
    spec:
      containers:
        - name: minio
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["server", "/data", "--console-address", ":{{ .Values.service.consolePort }}"]
          envFrom:
            - secretRef:
                name: {{ include "minio.fullname" . }}-creds
          ports:
            - name: api
              containerPort: {{ .Values.service.port }}
            - name: console
              containerPort: {{ .Values.service.consolePort }}
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "minio.selectorLabels" . | nindent 4 }}
  ports:
    - name: api
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
    - name: console
      port: {{ .Values.service.consolePort }}
      targetPort: {{ .Values.service.consolePort }}

