{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "minio.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "minio.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: api
      path: /minio/v2/metrics/cluster
      interval: 30s
      scrapeTimeout: 10s
{{- end }}
