apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-filedownloader-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    resourceNames: ["filedownloader-secret"]
    verbs: ["get"]